version: '3'
services:
  mongoDB:
    image: mongo 
    #ports:
    # - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin
    
  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
     - ME_CONFIG_MONGODB_SERVER=mongoDB
    depends_on:
      - mongoDB
  
  nodejs-backend:
    build: ./Series_Database/
    ports:
      - "3000:3000" # Adjust port as needed
    depends_on:
      - mongoDB

  nodejs-frontend:
    build: ./Series_Database_Frontend/
    ports:
    - "8080:8080" # Adjust port as needed
    depends_on:
      - nodejs-backend