# Use an official Node.js runtime as the base image
FROM node:latest

# Set environment variables
ENV API_HOST=localhost
ENV API_PORT=3000

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install && npm install express cors

# Copy the rest of the application source code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Define the startup command
CMD ["node", "app.js"]
